# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npm run release

      - name: Get new version
        id: version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Update package versions
        run: |
          # Update main package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.version.outputs.version }}\"/" package.json
          # Update dist package.json if it exists
          if [ -f "dist/package.json" ]; then
            sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.version.outputs.version }}\"/" dist/package.json
          fi

      - name: Build package
        run: npm run build:pkg

      - name: Prepare dist for publishing
        run: |
          cp package.json dist/
          cp README.md dist/
          cp LICENSE dist/
          sed -i '/"prepare": "husky"/d' dist/package.json
          sed -i 's/"name": "prism-ui"/"name": "@bluewavelabs\/prism-ui"/' dist/package.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Commit package.json
        run: |
          git add package.json
          git commit -m "chore: update package.json for version ${{ steps.version.outputs.version }}"
          git push origin master

      - name: Configure npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.npm_token }}

      - name: Publish package
        run: |
          cd dist
          npm publish --access public --ignore-scripts
