# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  build-storybook:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build-storybook
      - uses: actions/upload-artifact@v4
        with:
          name: storybook
          path: storybook-static

  release:
    needs: [build, build-storybook]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
      - run: npm ci
      - run: npm run build:pkg
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare dist for publishing
        run: |
          mkdir -p dist
          cp package.json dist/
          cp README.md dist/
          cp LICENSE dist/
          # Remove prepare script from package.json
          sed -i '/"prepare": "husky"/d' dist/package.json
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  verify-dist:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Verify dist contents
        run: |
          if [ ! -f "dist/package.json" ]; then
            echo "Error: package.json is missing from dist directory"
            exit 1
          fi
          if [ ! -d "dist/style" ]; then
            echo "Error: style directory is missing from dist directory"
            exit 1
          fi
          echo "Dist verification passed"

  publish-npm:
    needs: [build, build-storybook, release, verify-dist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd dist
          npm publish --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
